export default {
    ROLE_CUSTOMER: 'CUSTOMER',
    ROLE_BRANCH_ADMIN: 'BRANCH_ADMIN',
    ROLE_BRANCH_TECHNICIAN: 'BRANCH_TECHNICIAN',
    ROLE_COMPANY_ADMIN: 'COMPANY_ADMIN',
    ROLE_COMPANY_TECHNICIAN: 'COMPANY_TECHNICIAN',
  
   
}